
version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    networks:
      - monitoring
    ports:
      - 8008:8000

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - monitoring
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    networks:
      - monitoring
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
networks:
    monitoring:     
volumes:
  grafana_data: {}
  influxdb_data: {}

